// Generated by tools/sync-plugins.js; edit desktop plugin manifests then rerun the sync script.
const plugins = [
  {
    "id": "shiguang-schedule",
    "name": "课程表",
    "version": "3.14.0",
    "author": "基于 XingHeYuZhuan/shiguangschedule · U-Time适配",
    "icon": "calendar-days",
    "faIcon": "calendar-days",
    "description": "将时光课程表嵌入 Le 时间管理；周视图一屏显示周一到周日全部节次（默认 10 节），手机端无边距铺满整屏，视图切换与常用操作收在右上角「⋯」菜单；支持选择学校并登录教务一键导入、教务 XLSX/XLS/CSV/TSV/HTML 导入、多课表、课程管理、彩色课程块（默认开）与个性化配置、JSON/ICS 备份及时间块联动。",
    "permissions": [
      "ui",
      "storage",
      "blocks",
      "notify",
      "http",
      "events",
      "schoolImport"
    ],
    "entry": "main.js",
    "order": 1,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "web-collector",
    "name": "网页收集",
    "version": "1.5.0",
    "author": "U-Time内置",
    "icon": "bookmark",
    "faIcon": "bookmark",
    "description": "输入或拖入网址，自动识别网站名称与图标；支持多网址拖入、搜索、备注和应用内打开。卡片的编辑、刷新和删除操作可展开收起，长标题与备注可在卡片内查看。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 2,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "school-notice",
    "name": "学校通知网站",
    "version": "1.7.1",
    "author": "U-Time内置",
    "icon": "school",
    "faIcon": "school",
    "description": "输入学校公告/通知网址后自动识别常见高校 CMS 列表；对「服务端只吐空壳、列表靠 JS 渲染」的门户站点，会先命中已登记适配器，再尝试内嵌 JSON 状态和脚本里的通用公告/消息列表接口。支持会话登录、用户名密码和手动验证码，并可把公告转成 U-Time提醒。站点菜单会始终显示网站名称；点击异站点先切换公告且默认收起设置卡片，再点当前站点才展开登录网址等设置；右键站点弹出操作菜单（刷新 / 登录配置 / 编辑 / 打开 / 删除）。抓到新公告时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "notify",
      "http",
      "openUrl",
      "timeParse",
      "events"
    ],
    "entry": "main.js",
    "order": 3,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "pomodoro",
    "name": "番茄专注",
    "version": "0.8.0",
    "author": "U-Time内置",
    "icon": "hourglass-half",
    "faIcon": "hourglass-half",
    "description": "环形番茄钟：可关联任务，使用预设或精确到秒的自定义时长。桌面/Android 支持可开关的玻璃计时卡，可拖动玻璃片、调节五项参数，切换液态玻璃、柔焦玻璃和圆角切片三种材质。专注结束前可设置多个提醒时间点；专注与休息结束的通知、声音分别控制。支持内置和自定义提示音、试听，完成记录会计入统计并广播给其他插件。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "sound",
      "events"
    ],
    "entry": "main.js",
    "order": 4,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "weekly-report",
    "name": "周度报告",
    "version": "0.1.0",
    "author": "U-Time内置",
    "icon": "chart-column",
    "faIcon": "chart-column",
    "description": "按周汇总：每天的时间块分布、分类占比、任务完成度，一眼看清这一周过得怎么样。",
    "permissions": [
      "ui",
      "tasks",
      "blocks"
    ],
    "entry": "main.js",
    "order": 5,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "rss-reader",
    "name": "RSS 信息流",
    "version": "1.6.1",
    "author": "U-Time内置",
    "icon": "rss",
    "faIcon": "rss",
    "description": "订阅 RSS / Atom 源并聚合成一条信息流：多源并发抓取、RSS 2.0 / Atom / RDF 解析、按源与关键词过滤、未读与星标标记、顶栏一键添加源、摘要与原文正文展开、一键把带时间的条目转成U-Time提醒；粘贴网站首页还能自动发现订阅地址。抓到新内容时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http",
      "openUrl",
      "tasks",
      "blocks",
      "timeParse",
      "events"
    ],
    "entry": "main.js",
    "order": 6,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "gx-news",
    "name": "竞赛消息雷达",
    "version": "0.5.1",
    "author": "U-Time内置",
    "icon": "trophy",
    "faIcon": "trophy",
    "description": "多源竞赛消息雷达：内置摩课云竞赛平台、赛氪竞赛广场、我要参赛网三家，在「源」那一排一键切换；也能粘一个网址自己添加，RSS 订阅 / JSON 数据接口 / 网页列表自动识别，添加时真抓一次并报出条目数、认不出来说明原因。关键词过滤、类型与月份筛选、已读标记、每 10 分钟自动刷新，一键把消息转成U-Time提醒（正文没写时间时按接口给的报名截止日落期）。抓到新消息时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。注：微信小程序端受 request 合法域名白名单限制，只有摩课云一个源。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 7,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "chaoxing-notify",
    "name": "学习通",
    "version": "2.17.0",
    "author": "基于 dsh-user/chaoxing-notify-skill v2.0.0 · U-Time适配",
    "icon": "graduation-cap",
    "faIcon": "graduation-cap",
    "description": "学习通通知与待办：使用 notice.chaoxing.com 收件箱主路径（无需旧消息接口 IP 白名单），支持账号密码或 Cookie 登录、完整通知正文、分享码查询、作业/考试截止时间识别，可一键转为 U-Time提醒；通知支持移除（本机忽略，可恢复）与「浏览器打开（自动复用插件登录态）」；课程页可在「学年分组」与「开课时间总览」间切换：前者按学年分tab（默认最近学年）、学年内按完成状态三色卡片分组（红未完成/蓝正在进行/绿已完成），后者把全部学年按开课日期排成时间轴、同日合并；点击课程卡片展开该课的开课～结课时间与所属学期，并可带登录态打开该门课的课程门户；搜索框折叠为图标；待办作业按提交状态分「未截止未提交 / 已逾期未提交 / 已提交未截止 / 已提交已过期 / 已提交待批改」五档，截止已过不再从列表里消失，并可一键移除逾期未提交列表（仅本机隐藏，可恢复），探到已提交的从未提交段摘出；第五档专门收通知里没写结束时间、却已探到已提交的近期作业（老师不设截止时间时这类作业原本四档都不进，成绩没出就还不算完；只列近 60 天发布的，且不并进待办计数）；作业自动探测提交状态，已提交未批改的在标题后标「正在批改」；打开时可选「自动刷新 / 节流刷新」策略（悬停按钮可查看各自适用原因），默认自动刷新；新增「通知分类」页：顶部下拉按学年筛选（按中国学年制从通知时间推导，9 月至次年 8 月），旁边一排类型胶囊（全部/通知/作业/考试/签到，计数随学年走）；顶部保留刷新和更多操作，刷新策略、任务栏角标、完整同步、恢复移除和切换登录收进更多菜单；页面切换采用轻量导航，收件箱、待办和课程显示计数，详细作业状态在待办页查看；搜索支持拼音首字母缩写（bj→北京、dx→大学英语、25fh→25防火，收件箱与课程两处搜索均生效，数据表由 tools/gen-chaoxing-pinyin.js 生成，含多音字全部读音）。；Windows 任务栏动态显示未提交作业数，更多菜单内可开关，支持启动缓存恢复与每 5 分钟后台同步。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 8,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "cppu-notify",
    "name": "警大门户通知",
    "version": "1.35.1",
    "author": "基于 dsh-user/cppu-notify-skill v1.2.1 · U-Time适配（1.35.0 筛选新增年份与恢复默认、点外部收起下拉、空态可继续加载更早通知；1.26.1 教务查询遇网络抖动自动重发，报错摊平真实成因）",
    "icon": "building-columns",
    "faIcon": "building-columns",
    "description": "智慧警大门户通知：登录一次后自动恢复门户与教务会话。左侧「校园服务」提供教育邮箱、教务、学工、我的请假、一网通办、一卡通等入口；「教务」子菜单可进入学生选课、学生请假、警大成绩、创新学分和独立警大校历插件。警大成绩参考 cppu-helper 成绩页，展示总览、平均分与 GPA、分学期走势、学分进度、成绩分布、课程构成和课程列表，支持刷新、离线缓存及生成分享成绩单图片。创新学分按学期显示申报项目、级别、奖项、认定学分与审核状态。教务写操作仍由学校系统确认。教育邮箱和一卡通支持独立自动登录；一卡通可查看充值、消费与余额。通知支持自动刷新、分类、正文与附件阅读、转为提醒和微信推送联动。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse",
      "vault"
    ],
    "entry": "main.js",
    "order": 9,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "cppu-calendar",
    "name": "警大校历",
    "version": "0.3.0",
    "author": "U-Time内置",
    "icon": "calendar-days",
    "faIcon": "calendar-days",
    "description": "显示学期推算结束日、红色当前教学周、本周总节数与剩余节数（依据课程表当前课表）；支持同步教务学期、个人事项和离线查看。推算结束日不是官方放假安排。",
    "permissions": [
      "ui",
      "storage",
      "events",
      "notify"
    ],
    "entry": "main.js",
    "order": 9.5,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "wechat-push",
    "name": "微信提醒推送",
    "version": "1.10.0",
    "author": "U-Time内置",
    "icon": "comment-dots",
    "faIcon": "comment-dots",
    "description": "通过 PushPlus 把时间块、任务截止和插件新消息推送到微信，可细选消息源。插件消息攒批 2 分钟合并发送；支持 Token、Topic、测试消息和本地微信消息样式预览，预览复用实际发送的标题与正文格式。兼容旧版 Server酱配置。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 10,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "cn-holiday",
    "name": "中国节假日",
    "version": "0.3.0",
    "author": "U-Time内置 · 数据源 NateScarlet/holiday-cn",
    "icon": "calendar-day",
    "faIcon": "calendar-day",
    "description": "中国法定节假日、调休上班日和下次休息日；内置 2024–2026 离线数据，首屏不再探测未公布年份，缺失年份按需联网并缓存。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http"
    ],
    "entry": "main.js",
    "order": 11,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "exam-calendar",
    "name": "考试日历",
    "version": "0.3.3",
    "author": "your-name",
    "icon": "calendar-check",
    "faIcon": "calendar-check",
    "description": "大学生国家级考试倒计时与全流程查看（四六级/考研/教师资格/计算机等级/专四专八/普通话）。支持按单一考试筛选报名、准考证打印、口试/笔试等流程；CET 与普通话会提示各学校/考点/省份时间可能不同，并可直达全国报名系统。普通话水平测试无全国统一考试日期，按各省分批的报名与测试窗口标注。数据在构建时由官方公告采集后内嵌。列表行按「日期+考试名」与「倒计时+操作」两行排布，窄屏下考试名不再被操作按钮挤压截断。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 12,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "dorm-duty",
    "name": "轮换值日",
    "version": "1.8.0",
    "author": "U-Time内置",
    "icon": "broom",
    "faIcon": "broom",
    "description": "把宿舍值日等公共事务集中管理：可设多套独立轮换、成员周期和地点周期；地点按列表顺序每隔指定天数更换。支持假期、节日日期段暂停（结束后续排）、每轮多人当班、成员拖动排序、临时换人、到点提醒和加入今日任务。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "sound"
    ],
    "entry": "main.js",
    "order": 13,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "inbox-drop",
    "name": "拖入消息收纳",
    "version": "1.0.2",
    "author": "U-Time内置",
    "icon": "inbox",
    "faIcon": "inbox",
    "description": "把散落各处的消息拖进来就收好：微信/QQ 聊天文字、通知截图、网页段落、文件都能直接拖到面板上，自动识别来源平台、消息类型与日期时间，补一个可修正的确认条后收进应用收件箱，随时一键转成任务或时间块。聊天里长按选中的消息同样支持 Ctrl+V 粘贴；截图会作为附件跟随任务。不接收可执行文件，重复消息自动去重。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "notify",
      "sound",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 14,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "ai-chat",
    "name": "AI 对话",
    "version": "0.6.0",
    "author": "U-Time内置",
    "icon": "robot",
    "faIcon": "robot",
    "description": "在应用里直接问 AI：把本机任务、近三天时间块，以及消息类插件公开的现有列表摘要和新消息合并成数据快照。可总结今天、盘点本周、整理通知；建议逐条勾选后才写入任务与时间块，支持撤销。复用「设置 › AI 与自动任务」里的模型与密钥，凭据不进插件。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "ai",
      "messages",
      "notify",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 15,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "github-readme",
    "name": "GitHub 文档",
    "version": "1.3.0",
    "author": "U-Time",
    "icon": "code-branch",
    "faIcon": "code-branch",
    "description": "追踪 GitHub 仓库 README：支持 owner/repo 或仓库链接，正文按 GitHub Markdown 风格安全渲染。提供主题化页内编辑，一起修改名称、备注和图标；移除前确认，保存失败保留草稿。新提交可推送消息，首次加入不推历史；优先读取 GitHub 提交订阅，失败时使用 commits API 备用路径，错误只影响对应仓库。README 子目录路径自动处理。只读 README，不含 release、issue 和文件树。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 16,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "plugin-guide",
    "name": "插件使用说明",
    "version": "1.4.1",
    "author": "U-Time内置",
    "icon": "circle-question",
    "faIcon": "circle-question",
    "description": "按学习、效率、信息、生活与工具分类，用卡片快速查看每个内置插件的用途、使用步骤、平台支持和注意事项。",
    "permissions": [
      "ui",
      "notify",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 99,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  }
];
const byId = {};
plugins.forEach((plugin) => { byId[plugin.id] = plugin; });
module.exports = { plugins, byId };
